// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf";

/**
 * App-server projection of an image-generation result.
 *
 * This type is separate from the durable extension item so v2 can keep its
 * required-nullable field contract without changing rollout serialization.
 */
export type ImageGenerationItem = { id: string, status: string, revisedPrompt: string | null, prompt: string | null, result: string, transparentBackground: boolean | null, savedPath: AbsolutePathBuf | null, };
