// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SearchActivityKind } from "./SearchActivityKind";
import type { SearchActivityState } from "./SearchActivityState";

/**
 * Transient hosted search visibility alongside the ordered item stream.
 *
 * Scope previews by thread, turn, attempt and output index. Item IDs bind a
 * preview to the corresponding ordered search item in that attempt. A newer
 * attempt supersedes older previews. Ignore older attempts and clear previews
 * on terminal turns, thread replacement and cold replay. Only item/completed
 * creates history or supplies results; completed activity merely stops busy UI.
 */
export type SearchActivityNotification = { threadId: string, turnId: string,
/**
 * Increasing, JavaScript-safe integer generated by this server process.
 */
attemptId: number, outputIndex: number, itemId: string, kind: SearchActivityKind, state: SearchActivityState, };
