// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadWorkflowStatus } from "./ThreadWorkflowStatus";
import type { ThreadWorkflowStep } from "./ThreadWorkflowStep";

export type ThreadWorkflow = { threadId: string, runId: string, name: string, status: ThreadWorkflowStatus, currentStepIndex: number, steps: Array<ThreadWorkflowStep>, createdAt: number, updatedAt: number, };
