// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";
import type { ThreadWorkflowStatus } from "./ThreadWorkflowStatus";

export type ThreadWorkflow = { threadId: string, runId: string, name: string, status: ThreadWorkflowStatus, pendingInstruction: string | null, result: JsonValue, createdAt: number, updatedAt: number, };
