// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SearchSource } from "../SearchSource";
import type { JsonValue } from "../serde_json/JsonValue";
import type { WebSearchAction } from "./WebSearchAction";

/**
 * App-server projection of a hosted or standalone web search.
 *
 * This type is separate from the durable extension item so v2 can keep its
 * required-nullable field contract without changing rollout serialization.
 */
export type WebSearchItem = { id: string, query: string, action: WebSearchAction | null, results: Array<JsonValue> | null, source: SearchSource | null, };
