// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Provider payload retained without interpreting or inventing search results.
 * Only the Grok request/response owner may construct this canonical projection.
 */
export type XSearchItem = {
/**
 * Provider item identity, unique among retained items in this turn.
 */
id: string, callId: string, name: string, input: string, };
