use crate::JsonSchema;
use crate::TS;
use serde::Deserialize;
use serde::Serialize;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Deserialize, Serialize, TS, JsonSchema)]
#[serde(rename_all = "camelCase")]
#[ts(rename_all = "camelCase", export_to = "v2/")]
pub enum SearchActivityKind {
    Web,
}

#[derive(Serialize, Deserialize, Debug, Clone, Copy, PartialEq, Eq, JsonSchema, TS)]
#[serde(rename_all = "camelCase")]
#[ts(rename_all = "camelCase", export_to = "v2/")]
pub enum SearchActivityState {
    Running,
    /// Authoritative completion arrived, but is not yet necessarily retained.
    Completed,
    /// Discard the transient preview; this does not claim success or cancellation.
    Cleared,
}

/// Transient Web search visibility alongside the ordered item stream.
///
/// Scope previews by thread, turn, attempt and output index. Item IDs bind a
/// preview to the corresponding ordered Web item in that attempt. A newer
/// attempt supersedes older previews. Ignore older attempts and clear previews
/// on terminal turns, thread replacement and cold replay. Only item/completed
/// creates history or supplies results; completed activity merely stops busy UI.
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, JsonSchema, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export_to = "v2/")]
pub struct SearchActivityNotification {
    pub thread_id: String,
    pub turn_id: String,
    /// Increasing, JavaScript-safe integer generated by this server process.
    #[ts(type = "number")]
    pub attempt_id: u64,
    #[ts(type = "number")]
    pub output_index: u64,
    pub item_id: String,
    pub kind: SearchActivityKind,
    pub state: SearchActivityState,
}
