//! Extension crate for the `/goal` feature.

mod accounting;
mod analytics;
mod api;
mod events;
mod extension;
mod host_evaluate;
mod metrics;
mod policy;
mod runtime;
mod spec;
mod steering;
mod tool;

pub use api::GoalObjectiveUpdate;
pub use api::GoalService;
pub use api::GoalServiceError;
pub use api::GoalSetOutcome;
pub use api::GoalSetRequest;
pub use api::GoalTokenBudgetUpdate;
pub use extension::GoalExtension;
pub use extension::GoalExtensionConfig;
pub use extension::install_with_backend;
pub use extension::install_with_evaluator;
pub use host_evaluate::GoalEvaluatorDecision;
pub use host_evaluate::GoalEvaluatorError;
pub use host_evaluate::GoalEvaluatorParseError;
pub use host_evaluate::GoalEvaluatorVerdict;
pub use host_evaluate::GoalRoundEvaluationFuture;
pub use host_evaluate::GoalRoundEvaluationInput;
pub use host_evaluate::GoalRoundEvaluator;
pub use host_evaluate::HOST_BLOCKED_STREAK_THRESHOLD;
pub use host_evaluate::parse_goal_evaluator_verdict;
pub use policy::GoalCompletionAuthority;
pub use policy::GoalHow;
pub use policy::GoalPolicy;
pub use policy::GoalVerification;
pub use runtime::GoalRuntimeHandle;
pub use runtime::PreviousGoalSnapshot;
pub use spec::CREATE_GOAL_TOOL_NAME;
pub use spec::GET_GOAL_TOOL_NAME;
pub use spec::UPDATE_GOAL_TOOL_NAME;
pub use tool::CreateGoalRequest;
