//! Extension crate for the `/goal` feature.

mod accounting;
mod analytics;
mod api;
mod evaluator_prompt;
mod events;
mod extension;
mod guardian_skeptics;
mod host_evaluate;
mod host_verify;
mod metrics;
mod model_evaluator;
mod policy;
mod runtime;
mod skeptic_prompt;
mod spec;
mod steering;
mod tool;

pub use api::GoalObjectiveUpdate;
pub use api::GoalService;
pub use api::GoalServiceError;
pub use api::GoalSetOutcome;
pub use api::GoalSetRequest;
pub use api::GoalTokenBudgetUpdate;
pub use evaluator_prompt::EVALUATOR_SAMPLE_ATTEMPTS;
pub use evaluator_prompt::GoalEvaluatorEvidence;
pub use evaluator_prompt::build_goal_evaluator_user_payload;
pub use evaluator_prompt::goal_evaluator_evidence;
pub use evaluator_prompt::goal_evaluator_output_schema;
pub use evaluator_prompt::verdict_from_sample_attempts;
pub use extension::GoalExtension;
pub use extension::GoalExtensionConfig;
pub use extension::GoalHostCapabilities;
pub use extension::install_with_backend;
pub use extension::install_with_host_capabilities;
pub use guardian_skeptics::GuardianGoalSkepticPanel;
pub use host_evaluate::GoalEvaluatorDecision;
pub use host_evaluate::GoalEvaluatorError;
pub use host_evaluate::GoalEvaluatorParseError;
pub use host_evaluate::GoalEvaluatorVerdict;
pub use host_evaluate::GoalRoundEvaluationFuture;
pub use host_evaluate::GoalRoundEvaluationInput;
pub use host_evaluate::GoalRoundEvaluator;
pub use host_evaluate::HOST_BLOCKED_STREAK_THRESHOLD;
pub use host_evaluate::parse_goal_evaluator_verdict;
pub use host_verify::GoalSkepticError;
pub use host_verify::GoalSkepticPanel;
pub use host_verify::GoalSkepticPanelFuture;
pub use host_verify::GoalSkepticPanelInput;
pub use host_verify::GoalSkepticPanelVerdict;
pub use host_verify::GoalSkepticParseError;
pub use host_verify::GoalSkepticVote;
pub use host_verify::aggregate_skeptic_votes;
pub use host_verify::parse_goal_skeptic_vote;
pub use model_evaluator::ModelGoalRoundEvaluator;
pub use policy::GoalCompletionAuthority;
pub use policy::GoalHow;
pub use policy::GoalPolicy;
pub use policy::GoalVerification;
pub use policy::HOST_SKEPTIC_DEFAULT_COUNT;
pub use policy::HOST_SKEPTIC_MAX_COUNT;
pub use policy::HOST_SKEPTIC_MIN_COUNT;
pub use runtime::GoalRuntimeHandle;
pub use runtime::PreviousGoalSnapshot;
pub use skeptic_prompt::clamp_host_skeptic_count;
pub use skeptic_prompt::goal_skeptic_output_schema;
pub use spec::CREATE_GOAL_TOOL_NAME;
pub use spec::GET_GOAL_TOOL_NAME;
pub use spec::UPDATE_GOAL_TOOL_NAME;
pub use tool::CreateGoalRequest;
